//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBHDTCHUNG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSBHDTCHUNGEntities : DbContext
    {
        public CMSBHDTCHUNGEntities()
            : base("name=CMSBHDTCHUNGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brandname> Brandnames { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductAgent> ProductAgents { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<ProductActive> ProductActives { get; set; }
        public virtual DbSet<SendMT> SendMTs { get; set; }
        public virtual DbSet<PieName> PieNames { get; set; }
        public virtual DbSet<TempBrandname> TempBrandnames { get; set; }
        public virtual DbSet<TemplateMT> TemplateMTs { get; set; }
        public virtual DbSet<ProductWarranti> ProductWarrantis { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<TempSm> TempSms { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Link_API> Link_API { get; set; }
    }
}
