//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBHDTCHUNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link_API
    {
        public long Id { get; set; }
        public string Company { get; set; }
        public string Code { get; set; }
        public string KeyParam { get; set; }
        public string Domain { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public int Status { get; set; }
    }
}
